src/recaptcha-wrapper.js, src/recaptcha.js
Today I've done some research for one issue.
In the course of it I've found that `babel` always auto-inserts "use strict".
There is no [source.js](https://github.com/AlexKVal/bug_babel_webpack/blob/master/client.js) "use strict" in the source file.
But here it is present https://github.com/AlexKVal/bug_babel_webpack/blob/master/bundle.js#L47 in output file.
You can use my [simple trash project](https://github.com/AlexKVal/bug_babel_webpack) as a playground
and make sure of it by yourself. :)
=> Remove unnecessary "use strict".

package.json
Just some housekeeping; bumping version of babel to the most recent one. I think people are generally more likely to use a module if they see up-to-date deps :) thanks for working on this!
=> Bump babel version

src/recaptcha.js
as zero is a valid widgetId (apparently) since tonight. Although we couldn't find something in the docs, it breaks the recaptcha, because `explictRender` is evaluated two times on initialization:
=> handle widgetId 0

package.json
Don't bring a particular version of babel-runtime as direct dependency.  Can cause package bloat or duplication downstream for consumers.
=> make dependencies more friendly for consuming packages

package.json, src/recaptcha.js, test/recaptcha-spec.js, test/recaptcha-wrapper-spec.js
- removed dependency on createClass.
closes #38
=> Changed updated for react 15.5

src/recaptcha.js
Previously, if the call to execute() happened before
the script is asynchnonously loaded and fully rendered,
the Captcha would never execute.
=> Fix race on execute()

src/recaptcha.js
=> Remove rendered DOM on unmount

.babelrc, package.json
This adds build with no module transform on babel.
It enables webpack 3 to do scope hoisting.
=> Add es2015 module build

README.md, package.json
**Description:**
Move `react-async-script` from `peerDependencies` to `dependencies` so that it will be installed along with the `react-google-recaptcha` package
=> Fix: Dependencies

.babelrc
follow up to #86, paired with https://github.com/dozoisch/react-async-script/pull/29
- removes `transform-runtime` to remove all polyfills
I created an example repo here [test-build-webpack-babel-transform-runtime](https://github.com/hartzis/test-build-webpack-babel-transform-runtime) that runs a webpack bundle on a `react-google-recaptcha` component that includes `react-async-script`.
Simple entry point:
```
import react from 'react';
import ReCAPTCHA from 'react-google-recaptcha';
function Test() {
return (<ReCAPTCHA />)
}
```
I ran a reports *with* and **without** `transform-runtime`:
- **with** `transform-runtime` | [report-transform-runtime](https://hartzis.github.io/test-build-webpack-babel-transform-runtime/report-transform-runtime.html)
- has ~ `17kb parsed / 6kb gzip` worth of …
=> remove transform runtime

src/recaptcha.js
Resolves #99 
The component works fine when no `onChange` handler is provided, because an input is present with the current value. Because of that, submitting a form that this is used in will have the correct param.
I decided to accomplish this by providing a default value of `() => {}`. That way, existing code can call the callback, and things will still "work", even if no callback was provided.
=> Make the onChange prop not required

README.md
* Fixes the incorrect use of refs in the README.md examples (e.g. `recaptchaRef.execute()` instead of `recaptchaRef.current.execute()`.
=> Fix README.md examples and resolve #101

README.md
update google recaptcha link to go to directly to v2 docs
=> Update recaptcha link to v2

README.md
It's worth mentioning that you should pass `onChange` callback as well when initializing an invisible version. I spent some time trying to figure out how to get the token after calling `execute()`
=> Add onChange prop to invisible captcha

README.md, src/recaptcha.js, test/recaptcha.spec.js
Addresses #72, adds `executeAsync` to return a promise which resolves and rejects based on `handleChange` and `handleErrored`
=> executeAsync: Promised based execution GH-72

README.md
Hi,
this PR fixes the issue #176 improving the documentation adding the `asyncScriptOnLoad` definition because it could be difficult/ambiguous to know where the property come from. 
I also ordered the properties, which could be easier to read.
Open to any suggestion.
=> doc(readme): order common props + add asyncScriptOnLoad definition

.eslintrc.js, .prettierrc, .travis.yml, package-lock.json, package.json, test/.eslintrc
This upgrades jest to v26 and eslint to v7.
Also drops node 8 from travis and adds node 14.
To keep build tools up to date.
=> Upgrade build tools

package-lock.json, package.json, test/recaptcha.spec.js
Only impact seems to be from https://prettier.io/blog/2020/03/21/2.0.0.html#change-default-value-for-arrowparens-to-always-7430httpsgithubcomprettierprettierpull7430-by-kachkaevhttpsgithubcomkachkaev
I can make it so it is like before if you prefer, but having used the same change in another project for a few months, it grew on me and makes it easier for a lot of use cases. (see https://twitter.com/ManuelBieh/status/1181880524954050560)
=> Updated Prettier to v2

CHANGELOG.md, package-lock.json, package.json, src/recaptcha.js
Attempt to fix #171.
Additionally:
- remove the `reset()` call on unmount as it may be the root cause of #103.
- The `reset()` may also not have been necessary
- Issue #55 was specific to a react error using the same `ref`
- The fix for #55 with #73 included making a new `div` for each `explicitRender` which is probably all that is sufficient for the fix
- add a new `forceReset` method that calls `grecaptcha.reset()` without needing a `widgetId`
- this could be used if users experience errors related to #55 again 🤷 
@dozoisch could you possibly publish an alpha/beta of this that I can test? 
📓 If this does all work and simplifies things it will possibly require a major? 🤔
=> Remove timeout removal, remove component unmount

package-lock.json, package.json
Followed the guide in https://eslint.org/docs/user-guide/migrating-to-8.0.0 but given the low custom rules footprint nothing needed to b changed.
Ran `lint` and `lint:fix` scripts.
=> Updated ESLint to version 8

package-lock.json, package.json, test/.eslintrc, test/recaptcha-wrapper.spec.js, test/recaptcha.spec.js
This PR changes the tests to use @testing-library/react in preparation for react v18.
I tried to run the old tests against react@18-beta, but there seems to be no easy way with the react/test-utils.
With @testing-library/react@13-alpha and react@18-beta these rewritten tests pass.
=> Rewrite tests with @testing-library/react

README.md, src/recaptcha-wrapper.js, src/recaptcha.js
This change allows Google ReCaptcha Enterprise usage. You can set the windows global dynamic option, enterprise to true to get this functionality.
I have an Enterprise account and I tested there.
Please let me know if you have any questions/comments.
Thanks.
=> Allow Google ReCaptcha Enterprise
